export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const EMPTY_RESULTS = 'EMPTY_RESULTS';
export const FETCH_POPULAR = 'FETCH_POPULAR';
export const FETCH_POPULAR_SUCCESS = 'FETCH_POPULAR_SUCCESS';
export const FETCH_POPULAR_ERROR = 'FETCH_POPULAR_ERROR';
